name: dislike-cron
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route to recalculate dislikes in a row
        run: |
          curl --request POST \
          --url 'https://roger-bot.space/api/dislike-cron' \
          --header 'Authorization: Bearer ${{ secrets.CRON_API_KEY }}'
