name: rate-cron
on:
  schedule:
    - cron: "0 23,11 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route to calculate rate
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://rogerbot.tech/api/rate-cron
          configuration: '{ "method": "POST", "headers": {"Authorization": "Bearer ${{ secrets.CRON_API_KEY }}"} }'
          retry: true
