'install plantuml extension and java
'after that press opt+d or alt+d
'it'll open a preview of UML activity diagram
'more docs here: https://www.notion.so/maximkataev/Roger-Mental-Bot-5768c661baa349d8ab88bf8e69940685?pvs=4
 
@startuml
title Roger. Ежедневный замер настроения
start
  :находим в базе id предыдущего сообщения с замером настроения;
  :удаляем у предыдущего сообщения кнопки;
  :выбираем текстовку для нового сообщения;
  :отправляем сообщение для замера настроения с кнопками;
  :добавляем запись об отправленном сообщении в базу;
  if (пользователь заблокировал бота?) then (да)
    :ставим пользователю флаг is_active = false;
  else (нет)
  endif
  if (пользователь нажал на 🟠🔴) then (да)
    :удаляем у текущего сообщения кнопки;
    :записываем оценку настроения в базу;
    :берем последовательность сообщений для отправки;
    note left 
      объект из массива polls_answers
    endnote
    :отправляем текстовку "нашел сообщение другого пользователя";
    :удаляем кнопки с оценкой у предыдущего сообщения от другого пользователя;
    :отправляем сообщение с поддержкой;
    :отправляем сообщение "ты уже замерил настроение N раз";
    :считаем, сколько дней пользователь уже замерил настроение;
    note left 
      1. если пользователь замерил настроение 14 раз, 
      то ему доступна команда /mentalstata
      2. если пользователь замерил настроение 7 раз, 
      то Роджер предлагает ему стать волонтером
    endnote
    if (сегодня воскресенье?) then (да)
      :отправка текстовки "статистика твоего настроения за неделю";
      :генерация картинки со статистикой;
      :отправка картинки со статистикой настроения за неделю;
    else (нет)
    endif
    :поиск всех друзей пользователя в базе;
    while (пока не отправили сообщение всем друзьям)
      if (есть никнейм у пользователя?) then (да)
      else (нет)
        :генерируем диплинк на пользователя и зашиваем его в имя пользователя;
      endif
    :отправка сообщения другу;
    endwhile
  else (нет)
    :удаляем у текущего сообщения кнопки;
    :записываем оценку настроения в базу;
    :берем последовательность сообщений для отправки;
    note left 
      объект из массива polls_answers
    endnote
    :отправляем текстовку "круто, у тебя хорошее настроение";
    :выбираем текстовку "хочешь заполнить форму?";
    :выбираем form_id, привязанный к пользователю;
    :отправляем сообщение со ссылкой на форму;
    :отправляем сообщение "ты уже замерил настроение N раз";
    :считаем, сколько дней пользователь уже замерил настроение;
    note left 
      1. если пользователь замерил настроение 14 раз, 
      то ему доступна команда /mentalstata
      2. если пользователь замерил настроение 7 раз, 
      то Роджер предлагает ему стать волонтером
    endnote
    if (сегодня воскресенье?) then (да)
      :отправка текстовки "статистика твоего настроения за неделю";
      :генерация картинки со статистикой;
      :отправка картинки со статистикой настроения за неделю;
    else (нет)
    endif
  endif
end
@enduml