name: mood-cron-test
on:
  schedule:
    - cron: "/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route to ask for MOOD
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: roger-mental-bot-git-transfercron-df988d-ilyakukarkins-projects.vercel.app/api/ask-mood-cron
          configuration: '{ "method": "POST", "headers": {"Authorization": "Bearer ${{ secrets.CRON_API_KEY }}"} }'
          retry: true
